#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <windows.h>
#include <fstream>
#include <string>
#include <algorithm>
#include <vector>
#include <iomanip>
#include <set>
#include <map>
#include "Account.h"
#include "Card.h"
#include "Category.h"
#include "Date.h"
#include "Expense.h"
#include "functions.h"
#include "Report.h"
#include "ReportGenerator.h"
#include "Time.h"
#include "Wallet.h"